<?php
// Generated by DevGarden Push scope.php. Require this file from your plugin.
defined('ABSPATH') || exit;
foreach (['Token', 'Site', 'Store', 'Api', 'License', 'Updater', 'Connect', 'Push', 'AdminPage', 'Client'] as $c) {
    require_once __DIR__ . '/' . $c . '.php';
}
